// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnyQxCYHu7r_1rQIhdERp6JDUOa7Spvc',
    appId: '1:396960266134:web:5bb5dffcf4ad791bcc4fb7',
    messagingSenderId: '396960266134',
    projectId: 'sellwave-482dc',
    authDomain: 'sellwave-482dc.firebaseapp.com',
    storageBucket: 'sellwave-482dc.appspot.com',
    measurementId: 'G-G0M53RQ8X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbQagXjbaoCxaN-qYEUU0ZV8cMmwvOtkM',
    appId: '1:396960266134:android:6dd27e8b57383b04cc4fb7',
    messagingSenderId: '396960266134',
    projectId: 'sellwave-482dc',
    storageBucket: 'sellwave-482dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUDc78TLMqcTQamWlMtU20FY79cFERd-o',
    appId: '1:396960266134:ios:1f8c4541345c107bcc4fb7',
    messagingSenderId: '396960266134',
    projectId: 'sellwave-482dc',
    storageBucket: 'sellwave-482dc.appspot.com',
    iosBundleId: 'com.example.abAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUDc78TLMqcTQamWlMtU20FY79cFERd-o',
    appId: '1:396960266134:ios:1f8c4541345c107bcc4fb7',
    messagingSenderId: '396960266134',
    projectId: 'sellwave-482dc',
    storageBucket: 'sellwave-482dc.appspot.com',
    iosBundleId: 'com.example.abAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnyQxCYHu7r_1rQIhdERp6JDUOa7Spvc',
    appId: '1:396960266134:web:cc627a5e070da125cc4fb7',
    messagingSenderId: '396960266134',
    projectId: 'sellwave-482dc',
    authDomain: 'sellwave-482dc.firebaseapp.com',
    storageBucket: 'sellwave-482dc.appspot.com',
    measurementId: 'G-71332BTSR0',
  );
}
